# Generated by Django 5.2.2 on 2025-06-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'комментария', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
